
kind: pipeline
name: java8

platform:
  arch: amd64

steps:
- name: prepare-dependencies
  image: omz-ci-tools
  pull: never
  commands:
  - artifact-dl-java maven/org.json:json:20211205
  - artifact-dl-java omz/org.omegazero.common:omz-common:release
  - artifact-dl-java omz/org.omegazero.net:omz-netlib:release

- name: prepare-source
  image: omz-ci-tools
  pull: never
  commands:
  - mkdir build
  - setversion base/main/java/org/omegazero/proxy/core/Proxy.java

- name: build-base
  image: openjdk:8
  commands:
  - mkdir -p build/base/bin
  - find base/main/java -iname "*.java" > build/base/srcfiles
  - javac -version -Werror -verbose -d build/base/bin -cp json-20211205.jar:omz-common-release.jar:omz-netlib-release.jar @build/base/srcfiles
  - cp -r base/main/resources/* build/base/bin/
  - jar cf build-base.jar -C build/base/bin .
  depends_on:
  - prepare-dependencies
  - prepare-source

- name: merge-jars
  image: openjdk:8
  commands:
  - (cd build/base/bin; unzip -uo ../../../json-20211205.jar)
  - (cd build/base/bin; unzip -uo ../../../omz-common-release.jar)
  - (cd build/base/bin; unzip -uo ../../../omz-netlib-release.jar)
  - rm -r build/base/bin/META-INF
  - jar cf build-base-all.jar -C build/base/bin .
  depends_on:
  - build-base

- name: publish
  image: omz-ci-tools
  pull: never
  commands:
  - artifact-push-java build-base.jar omz/org.omegazero.proxy:omz-proxy
  - artifact-push-java build-base-all.jar omz/org.omegazero.proxy:omz-proxy-all
  depends_on:
  - build-base
  - merge-jars
  environment:
    OMZ_ARTIFACT_PUSH_TOKEN:
      from_secret: artifact_push_token
