
kind: pipeline
name: java8

platform:
  arch: amd64

steps:
- name: prepare-dependencies
  image: omz-ci-tools
  pull: never
  commands:
  - artifact-dl-java maven/org.json:json:20211205
  - artifact-dl-java omz/org.omegazero.common:omz-common:release
  - artifact-dl-java omz/org.omegazero.net:omz-netlib-nio:release
  - artifact-dl-java omz/org.omegazero.http:omz-http:latest

- name: prepare-source
  image: omz-ci-tools
  pull: never
  commands:
  - mkdir build
  - setversion base/main/java/org/omegazero/proxy/core/Proxy.java
  - setversion http1/main/resources/plugin.cfg
  - setversion http2/main/resources/plugin.cfg
  - curl -G "https://omegazero.org/site/software/r/license_bin_full.php" --data-urlencode "srcurl=$DRONE_REPO_LINK/src/commit/$DRONE_COMMIT" > LICENSE_BIN

- name: build-base
  image: o-jvm-build
  pull: never
  commands:
  - mkdir -p build/base/META-INF
  - cp LICENSE_BIN build/base/META-INF/LICENSE
  - make base BINDIR=build
  depends_on:
  - prepare-dependencies
  - prepare-source

- name: build-http1
  image: o-jvm-build
  pull: never
  commands:
  - mkdir -p build/http1/META-INF
  - cp LICENSE_BIN build/http1/META-INF/LICENSE
  - make http1 BINDIR=build
  depends_on:
  - build-base

- name: build-http2
  image: o-jvm-build
  pull: never
  commands:
  - mkdir -p build/http2/META-INF
  - cp LICENSE_BIN build/http2/META-INF/LICENSE
  - make http2 BINDIR=build
  depends_on:
  - build-base

- name: merge-jars
  image: o-jvm-build
  pull: never
  commands:
  - mkdir build/base/licenses
  - mv build/base/META-INF/LICENSE build/base/licenses/LICENSE_org_omegazero_proxy
  - (cd build/base; unzip -uo ../../json-20211205.jar)
  - curl -G "https://raw.githubusercontent.com/stleary/JSON-java/master/LICENSE" > build/base/licenses/LICENSE_org_json
  - (cd build/base; unzip -uo ../../omz-common-release.jar)
  - "[ ! -f build/base/bin/META-INF/LICENSE ] || mv build/base/META-INF/LICENSE build/base/licenses/LICENSE_org_omegazero_common"
  - (cd build/base; unzip -uo ../../omz-netlib-nio-release.jar)
  - "[ ! -f build/base/bin/META-INF/LICENSE ] || mv build/base/META-INF/LICENSE build/base/licenses/LICENSE_org_omegazero_net"
  - (cd build/base; unzip -uo ../../omz-http-latest.jar)
  - "[ ! -f build/base/META-INF/LICENSE ] || mv build/base/META-INF/LICENSE build/base/licenses/LICENSE_org_omegazero_http"
  - rm -r build/base/META-INF/*
  - mv build/base/licenses/* build/base/META-INF
  - jar cf build-base-all.jar -C build/base .
  depends_on:
  - build-base

- name: publish
  image: omz-ci-tools
  pull: never
  commands:
  - artifact-push-java build/omz-proxy3.jar omz/org.omegazero.proxy:omz-proxy
  - artifact-push-java build-base-all.jar omz/org.omegazero.proxy:omz-proxy-all
  - artifact-push-java build/http1.jar omz/org.omegazero.proxy:http1
  - artifact-push-java build/http2.jar omz/org.omegazero.proxy:http2
  depends_on:
  - build-base
  - build-http1
  - build-http2
  - merge-jars
  environment:
    OMZ_ARTIFACT_PUSH_TOKEN:
      from_secret: artifact_push_token
